### ISSUE TITLE
Can't find config.ini file

### ISSUE THREAD

**Issue by alucardxs** [muldjord/leddy#2]
Hello dude,

Thanks for your project, it works pretty well !
Just one question, I can't find the config.ini file you're using the change default theme path (for example).
Leddy is on but no config.ini to be found, where is it supposed to be ?

Kind regards.

**Comment by muldjord** [comment]
You're welcome! The config.ini file is created in the same path as the executable when it is run. You should be able to find it there.

**Comment by alucardxs** [comment]
Thanks, still no config.ini file, that's weird imo as it probably needs the config file to go to the right directory : when I change parameters in the theme.xml (default folder), it works but the brightness, it's a no go.

**Comment by muldjord** [comment]
If I delete my config.ini and rerun the Leddy executable it creates a config.ini in the same folder as the executable as expected. My best guess is that maybe you have permission problems disallowing it to create it. It will run with default options if no config.ini can be created which can explain why it still works for you.

**Comment by muldjord** [comment]
Closing, hope you figured this out.
